<?php
$tipos = ['acesso' => t('auditoria.tipo.acesso'), 'estudos' => t('auditoria.tipo.estudos'), 'clinica' => t('auditoria.tipo.clinica'), 'sla_medicos' => t('auditoria.tipo.sla_medicos')];
$formatarDuracao = static function (mixed $segundos): string {
    if ($segundos === null || $segundos === '') return '—';
    $total = max(0, (int) $segundos);
    $horas = intdiv($total, 3600);
    $minutos = intdiv($total % 3600, 60);
    return $horas > 0 ? $horas . 'h' . str_pad((string) $minutos, 2, '0', STR_PAD_LEFT) . 'min' : $minutos . 'min';
};
$query = static function (array $extras = []) use ($tipo, $filtros): string {
    return http_build_query(array_filter(array_merge([
        'tipo' => $tipo, 'periodo' => $filtros['atalho'], 'data_de' => $filtros['data_de'], 'data_ate' => $filtros['data_ate'],
        'usuario_id' => $filtros['usuario_id'], 'grupo_id' => $filtros['grupo_id'],
    ], $extras), static fn($valor) => $valor !== null && $valor !== ''));
};
?>
<div class="page-header"><h1><i class="fa fa-shield-halved"></i> <?= htmlspecialchars(t('auditoria.titulo')) ?></h1><p><?= htmlspecialchars(t('auditoria.subtitulo')) ?></p></div>
<div class="card mb-3"><div class="card-body">
<form method="GET" action="/relatorios/auditoria" class="row g-2 align-items-end">
  <div class="col-md-3"><label><?= htmlspecialchars(t('auditoria.filtro.tipo')) ?></label><select name="tipo" class="form-select" onchange="this.form.submit()"><?php foreach ($tipos as $key => $label): ?><option value="<?= $key ?>" <?= $key === $tipo ? 'selected' : '' ?><?= $key !== 'sla_medicos' && !$permissoes->podeLer(['acesso'=>'auditoria_acesso','estudos'=>'auditoria_estudos','clinica'=>'auditoria_clinica'][$key] ?? 'sla_medicos') ? ' disabled' : '' ?>><?= htmlspecialchars($label) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-2"><label><?= htmlspecialchars(t('auditoria.filtro.periodo')) ?></label><select name="periodo" class="form-select"><option value="hoje" <?= $filtros['atalho']==='hoje'?'selected':'' ?>><?= htmlspecialchars(t('auditoria.periodo.hoje')) ?></option><option value="sete_dias" <?= $filtros['atalho']==='sete_dias'?'selected':'' ?>><?= htmlspecialchars(t('auditoria.periodo.sete_dias')) ?></option><option value="mes" <?= $filtros['atalho']==='mes'?'selected':'' ?>><?= htmlspecialchars(t('auditoria.periodo.mes')) ?></option><option value="customizado" <?= $filtros['atalho']==='customizado'?'selected':'' ?>><?= htmlspecialchars(t('auditoria.periodo.customizado')) ?></option></select></div>
  <div class="col-md-2"><label><?= htmlspecialchars(t('auditoria.filtro.data_de')) ?></label><input type="date" name="data_de" value="<?= $filtros['data_de'] ?>" class="form-control"></div>
  <div class="col-md-2"><label><?= htmlspecialchars(t('auditoria.filtro.data_ate')) ?></label><input type="date" name="data_ate" value="<?= $filtros['data_ate'] ?>" class="form-control"></div>
  <div class="col-md-2"><label><?= htmlspecialchars(t('auditoria.filtro.usuario')) ?></label><select name="usuario_id" class="form-select"><option value=""><?= htmlspecialchars(t('auditoria.todos')) ?></option><?php foreach ($opcoes['usuarios'] as $u): ?><option value="<?= (int)$u['id'] ?>" <?= (int)$filtros['usuario_id']===(int)$u['id']?'selected':'' ?>><?= htmlspecialchars($u['name']) ?></option><?php endforeach; ?></select></div>
  <div class="col-md-2"><label><?= htmlspecialchars(t('auditoria.filtro.grupo')) ?></label><select name="grupo_id" class="form-select"><option value=""><?= htmlspecialchars(t('auditoria.todos')) ?></option><?php foreach ($opcoes['grupos'] as $g): ?><option value="<?= (int)$g['id'] ?>" <?= (int)$filtros['grupo_id']===(int)$g['id']?'selected':'' ?>><?= htmlspecialchars($g['nome']) ?></option><?php endforeach; ?></select></div>
	  <div class="col-md-1"><button class="btn btn-primary w-100"><i class="fa fa-search"></i> <?= htmlspecialchars(t('auditoria.buscar')) ?></button></div>
	</form></div></div>
<div class="card mb-3"><div class="card-body d-flex flex-wrap justify-content-between align-items-center gap-2"><div><strong><?= htmlspecialchars($tipos[$tipo]) ?></strong><div class="text-muted small mt-1"><?= htmlspecialchars(t('auditoria.contexto.subtitulo')) ?></div></div><div class="d-flex gap-2"><a class="btn btn-outline-danger btn-sm" href="/relatorios/auditoria/exportar?<?= htmlspecialchars($query(['formato' => 'pdf'])) ?>"><i class="fa fa-file-pdf"></i> <?= htmlspecialchars(t('auditoria.exportar.pdf')) ?></a><a class="btn btn-outline-success btn-sm" href="/relatorios/auditoria/exportar?<?= htmlspecialchars($query(['formato' => 'csv'])) ?>"><i class="fa fa-file-csv"></i> <?= htmlspecialchars(t('auditoria.exportar.csv')) ?></a></div></div></div>
<div class="card"><div class="card-header d-flex justify-content-between"><strong><?= htmlspecialchars(t('auditoria.contexto.titulo')) ?></strong><span class="badge bg-secondary"><?= (int)$total ?> <?= htmlspecialchars(t('auditoria.eventos')) ?></span></div><div class="table-responsive"><table class="table table-hover mb-0"><thead><tr><th><?= htmlspecialchars(t('auditoria.coluna.data')) ?></th><th><?= htmlspecialchars(t('auditoria.coluna.autor')) ?></th><?php if ($tipo === 'clinica'): ?><th><?= htmlspecialchars(t('auditoria.coluna.assumido_em')) ?></th><th><?= htmlspecialchars(t('auditoria.coluna.tempo')) ?></th><th><?= htmlspecialchars(t('auditoria.coluna.peer_review')) ?></th><?php endif; ?><th><?= htmlspecialchars(t('auditoria.coluna.evento')) ?></th><th><?= htmlspecialchars(t('auditoria.coluna.entidade')) ?></th><th>IP</th><th><?= htmlspecialchars(t('auditoria.coluna.regiao')) ?></th><th><?= htmlspecialchars(t('auditoria.coluna.contexto')) ?></th></tr></thead><tbody>
<?php if (!$linhas): ?><tr><td colspan="<?= $tipo === 'clinica' ? 10 : 7 ?>" class="text-center text-muted py-4"><?= htmlspecialchars(t('auditoria.vazio')) ?></td></tr><?php endif; ?>
<?php foreach ($linhas as $row): ?><tr><td><?= htmlspecialchars(date('d/m/Y H:i:s', strtotime($row['created_at']))) ?></td><td><?= htmlspecialchars($row['usuario_nome'] ?: t('auditoria.sistema')) ?></td><?php if ($tipo === 'clinica'): ?><td><?= !empty($row['assumido_em']) ? htmlspecialchars(date('d/m/Y H:i:s', strtotime($row['assumido_em']))) : '—' ?></td><td><?= htmlspecialchars($formatarDuracao($row['duracao_seg'] ?? null)) ?></td><td><?= htmlspecialchars((int)($row['possui_peer_review'] ?? 0) === 1 ? t('auditoria.sim') : t('auditoria.nao')) ?></td><?php endif; ?><td><?= htmlspecialchars($apresentacao->evento((string) $row['action'])) ?></td><td><?= htmlspecialchars($apresentacao->entidade((string) $row['entity'], !empty($row['entity_id']) ? (int) $row['entity_id'] : null)) ?></td><td><?= htmlspecialchars($row['ip'] ?: '—') ?></td><td><?= htmlspecialchars($row['region_code'] ?: '—') ?></td><td><?= htmlspecialchars($apresentacao->contexto((string) $row['action'], $row['details'] ?? null)) ?></td></tr><?php endforeach; ?>
</tbody></table></div></div>
