<div class="d-flex justify-content-between align-items-center mb-4">
    <div><h1 class="h3 mb-1"><i class="fa fa-desktop me-2"></i><?= htmlspecialchars(t('voxel_desktop.title')) ?></h1><p class="text-muted mb-0"><?= htmlspecialchars(t('voxel_desktop.subtitle')) ?></p></div>
    <a class="btn btn-outline-secondary" href="/platform/negocios/<?= (int)$tenant['id'] ?>/edit"><?= htmlspecialchars(t('voxel_desktop.back')) ?></a>
</div>
<?php if (!empty($_SESSION['success'])): ?><div class="alert alert-success"><?= htmlspecialchars($_SESSION['success']); unset($_SESSION['success']); ?></div><?php endif; ?>
<?php if (!empty($_SESSION['error'])): ?><div class="alert alert-danger"><?= htmlspecialchars($_SESSION['error']); unset($_SESSION['error']); ?></div><?php endif; ?>
<div class="alert alert-warning"><strong><?= htmlspecialchars(t('voxel_desktop.disabled_title')) ?></strong> <?= htmlspecialchars(t('voxel_desktop.disabled_help')) ?></div>
<div class="card shadow-sm mb-4"><div class="card-body"><h2 class="h5 mb-3"><?= htmlspecialchars(t('voxel_desktop.destination_new')) ?></h2>
<form method="post" action="/platform/negocios/<?= (int)$tenant['id'] ?>/voxel-desktop/destinations">
<input type="hidden" name="_csrf_token" value="<?= htmlspecialchars($csrfToken) ?>">
<div class="row g-3"><div class="col-md-4"><label class="form-label"><?= htmlspecialchars(t('voxel_desktop.name')) ?></label><input class="form-control" name="nome" required maxlength="120"></div><div class="col-md-4"><label class="form-label"><?= htmlspecialchars(t('voxel_desktop.router_id')) ?></label><input class="form-control" name="router_id" required maxlength="120"></div><div class="col-md-4"><label class="form-label"><?= htmlspecialchars(t('voxel_desktop.site_id')) ?></label><input class="form-control" name="site_id" required maxlength="120"></div>
<div class="col-md-6"><label class="form-label"><?= htmlspecialchars(t('voxel_desktop.issuer')) ?></label><input class="form-control" name="issuer_of_patient_id_normalized" maxlength="255"><div class="form-text"><?= htmlspecialchars(t('voxel_desktop.issuer_help')) ?></div></div><div class="col-md-6"><label class="form-label"><?= htmlspecialchars(t('voxel_desktop.institution')) ?></label><input class="form-control" name="institution_name" maxlength="255"><div class="form-text"><?= htmlspecialchars(t('voxel_desktop.institution_help')) ?></div></div>
<div class="col-md-6"><label class="form-label"><?= htmlspecialchars(t('voxel_desktop.router_token')) ?></label><input class="form-control" type="password" name="router_token" autocomplete="new-password"><div class="form-text"><?= htmlspecialchars(t('voxel_desktop.router_token_help')) ?></div></div><div class="col-md-3"><label class="form-label"><?= htmlspecialchars(t('voxel_desktop.profile')) ?></label><input class="form-control" value="submission/document" readonly></div><div class="col-md-3"><label class="form-label"><?= htmlspecialchars(t('voxel_desktop.environment')) ?></label><input class="form-control" value="<?= htmlspecialchars(t('voxel_desktop.homologation')) ?>" readonly></div></div>
<input type="hidden" name="profile" value="submission_document"><input type="hidden" name="ambiente" value="homologacao"><button class="btn btn-primary mt-4" type="submit"><?= htmlspecialchars(t('voxel_desktop.save_disabled')) ?></button></form></div></div>
<div class="card shadow-sm"><div class="card-body"><h2 class="h5 mb-3"><?= htmlspecialchars(t('voxel_desktop.destinations')) ?></h2><div class="table-responsive"><table class="table table-sm"><thead><tr><th><?= htmlspecialchars(t('voxel_desktop.name')) ?></th><th><?= htmlspecialchars(t('voxel_desktop.profile')) ?></th><th><?= htmlspecialchars(t('voxel_desktop.status')) ?></th><th><?= htmlspecialchars(t('voxel_desktop.updated')) ?></th></tr></thead><tbody><?php foreach ($destinations as $destination): ?><tr><td><?= htmlspecialchars((string)$destination['nome']) ?></td><td><?= htmlspecialchars((string)$destination['profile']) ?></td><td><span class="badge text-bg-secondary"><?= htmlspecialchars(t('voxel_desktop.disabled')) ?></span></td><td><?= htmlspecialchars((string)$destination['updated_at']) ?></td></tr><?php endforeach; ?><?php if (!$destinations): ?><tr><td colspan="4" class="text-muted"><?= htmlspecialchars(t('voxel_desktop.empty')) ?></td></tr><?php endif; ?></tbody></table></div></div></div>
