<?php
// Sincronização de runtime da interface de ambiente e teste manual sem automação.
// Control-plane Voxel Desktop: habilitação explícita não cria fila nem dispara liberação automática.
$escape = static fn(mixed $value): string => htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8');
$manualDestinations = array_filter($destinations, static fn(array $d): bool => !empty($d['enabled']) && (string)$d['ambiente'] === 'homologacao');
?>
<div class="d-flex justify-content-between align-items-center mb-4">
    <div><h1 class="h3 mb-1"><i class="fa fa-desktop me-2"></i><?= $escape(t('voxel_desktop.title')) ?></h1><p class="text-muted mb-0"><?= $escape(t('voxel_desktop.subtitle')) ?></p></div>
    <a class="btn btn-outline-secondary" href="/platform/negocios/<?= (int)$tenant['id'] ?>/edit"><?= $escape(t('voxel_desktop.back')) ?></a>
</div>
<?php if (!empty($_SESSION['success'])): ?><div class="alert alert-success"><?= $escape($_SESSION['success']); unset($_SESSION['success']); ?></div><?php endif; ?>
<?php if (!empty($_SESSION['error'])): ?><div class="alert alert-danger"><?= $escape($_SESSION['error']); unset($_SESSION['error']); ?></div><?php endif; ?>
<div class="alert alert-warning"><strong><?= $escape(t('voxel_desktop.safety_title')) ?></strong> <?= $escape(t('voxel_desktop.safety_help')) ?></div>

<div class="card border-info shadow-sm mb-4"><div class="card-body d-flex flex-wrap align-items-center justify-content-between gap-3"><div><h2 class="h5 mb-1"><i class="fa fa-folder-tree me-1"></i>PHILIPS NON-DICOM — PDF/SMB</h2><p class="small text-muted mb-0">Configure o destino de homologação, salve a senha cifrada e execute <strong>Testar conexão SMB</strong> no Delivery Hub. O teste técnico não cria job clínico; a entrega PDF continua manual, unitária e sem XML.</p></div><a class="btn btn-outline-info" href="/platform/negocios/<?= (int)$tenant['id'] ?>/report-delivery">Configurar e testar SMB</a></div></div>

<div class="card shadow-sm mb-4"><div class="card-body">
    <h2 class="h5 mb-3" id="destination-form-title"><?= $escape(t('voxel_desktop.destination_new')) ?></h2>
    <form id="voxel-destination-form" method="post" action="/platform/negocios/<?= (int)$tenant['id'] ?>/voxel-desktop/destinations">
        <input type="hidden" name="_csrf_token" value="<?= $escape($csrfToken) ?>">
        <div class="row g-3">
            <div class="col-md-4"><label class="form-label" for="vd-name"><?= $escape(t('voxel_desktop.name')) ?></label><input id="vd-name" class="form-control" name="nome" required maxlength="120"></div>
            <div class="col-md-4"><label class="form-label" for="vd-router"><?= $escape(t('voxel_desktop.router_id')) ?></label><input id="vd-router" class="form-control" name="router_id" required maxlength="120"><div class="form-text"><?= $escape(t('voxel_desktop.identifier_help')) ?></div></div>
            <div class="col-md-4"><label class="form-label" for="vd-site"><?= $escape(t('voxel_desktop.site_id')) ?></label><input id="vd-site" class="form-control" name="site_id" required maxlength="120"><div class="form-text"><?= $escape(t('voxel_desktop.identifier_help')) ?></div></div>
            <div class="col-md-6"><label class="form-label" for="vd-issuer"><?= $escape(t('voxel_desktop.issuer')) ?></label><input id="vd-issuer" class="form-control" name="issuer_of_patient_id_normalized" maxlength="255"><div class="form-text"><?= $escape(t('voxel_desktop.issuer_help')) ?></div></div>
            <div class="col-md-6"><label class="form-label" for="vd-institution"><?= $escape(t('voxel_desktop.institution')) ?></label><input id="vd-institution" class="form-control" name="institution_name" maxlength="255"><div class="form-text"><?= $escape(t('voxel_desktop.institution_help')) ?></div></div>
            <div class="col-md-6"><label class="form-label" for="vd-token"><?= $escape(t('voxel_desktop.router_token')) ?></label><input id="vd-token" class="form-control" type="password" name="router_token" autocomplete="new-password"><div class="form-text" id="vd-token-help"><?= $escape(t('voxel_desktop.router_token_help')) ?></div></div>
            <div class="col-md-3"><label class="form-label"><?= $escape(t('voxel_desktop.profile')) ?></label><input class="form-control" value="submission/document" readonly><input type="hidden" name="profile" value="submission_document"></div>
            <div class="col-md-3"><label class="form-label" for="vd-environment"><?= $escape(t('voxel_desktop.environment')) ?></label><select id="vd-environment" class="form-select" name="ambiente"><option value="homologacao"><?= $escape(t('voxel_desktop.homologation')) ?></option><option value="producao"><?= $escape(t('voxel_desktop.production')) ?></option></select><div class="form-text"><?= $escape(t('voxel_desktop.environment_help')) ?></div></div>
        </div>
        <div class="mt-4 d-flex gap-2"><button class="btn btn-primary" type="submit"><?= $escape(t('voxel_desktop.save_disabled')) ?></button><button class="btn btn-outline-secondary d-none" id="vd-cancel-edit" type="button"><?= $escape(t('voxel_desktop.cancel_edit')) ?></button></div>
        <div class="form-text mt-2"><?= $escape(t('voxel_desktop.save_disabled_help')) ?></div>
    </form>
</div></div>

<div class="card shadow-sm mb-4"><div class="card-body"><h2 class="h5 mb-3"><?= $escape(t('voxel_desktop.destinations')) ?></h2><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th><?= $escape(t('voxel_desktop.name')) ?></th><th><?= $escape(t('voxel_desktop.environment')) ?></th><th><?= $escape(t('voxel_desktop.status')) ?></th><th><?= $escape(t('voxel_desktop.automatic_status')) ?></th><th><?= $escape(t('voxel_desktop.updated')) ?></th><th class="text-end"><?= $escape(t('voxel_desktop.actions')) ?></th></tr></thead><tbody>
<?php foreach ($destinations as $destination): ?>
    <?php $json=$escape(json_encode($destination, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_HEX_AMP|JSON_HEX_TAG)); $isProd=(string)$destination['ambiente']==='producao'; ?>
    <tr><td><strong><?= $escape($destination['nome']) ?></strong><div class="small text-muted"><?= $escape((string)$destination['profile']) ?></div></td><td><span class="badge <?= $isProd?'text-bg-dark':'text-bg-info' ?>"><?= $escape($isProd?t('voxel_desktop.production'):t('voxel_desktop.homologation')) ?></span></td><td><?= !empty($destination['enabled'])?'<span class="badge text-bg-success">'.$escape(t('voxel_desktop.enabled')).'</span>':'<span class="badge text-bg-secondary">'.$escape(t('voxel_desktop.disabled')).'</span>' ?></td><td><span class="badge text-bg-light border text-dark"><?= $escape(t('voxel_desktop.manual_only')) ?></span></td><td><?= $escape($destination['updated_at']) ?></td><td class="text-end"><div class="d-flex flex-column gap-2 align-items-end"><button class="btn btn-sm btn-outline-primary vd-edit" data-destination="<?= $json ?>" type="button"><?= $escape(t('voxel_desktop.edit')) ?></button>
    <?php if (empty($destination['enabled'])): ?><form method="post" action="/platform/negocios/<?= (int)$tenant['id'] ?>/voxel-desktop/destinations/<?= (int)$destination['id'] ?>/activate" class="text-start border rounded p-2"><input type="hidden" name="_csrf_token" value="<?= $escape($csrfToken) ?>"><div class="form-check small"><input class="form-check-input" id="vd-activate-<?= (int)$destination['id'] ?>" name="confirm_activation" value="1" type="checkbox" required><label class="form-check-label" for="vd-activate-<?= (int)$destination['id'] ?>"><?= $escape(t('voxel_desktop.confirm_activation')) ?></label></div><?php if ($isProd): ?><div class="form-check small mt-1"><input class="form-check-input" id="vd-production-<?= (int)$destination['id'] ?>" name="confirm_production_activation" value="1" type="checkbox" required><label class="form-check-label fw-semibold" for="vd-production-<?= (int)$destination['id'] ?>"><?= $escape(t('voxel_desktop.confirm_production')) ?></label></div><?php endif; ?><button class="btn btn-sm btn-success mt-2" type="submit"><?= $escape(t('voxel_desktop.activate')) ?></button></form>
    <?php else: ?><form method="post" action="/platform/negocios/<?= (int)$tenant['id'] ?>/voxel-desktop/destinations/<?= (int)$destination['id'] ?>/deactivate"><input type="hidden" name="_csrf_token" value="<?= $escape($csrfToken) ?>"><input type="hidden" name="confirm_deactivation" value="1"><button class="btn btn-sm btn-outline-danger" type="submit" onclick="return confirm('<?= $escape(t('voxel_desktop.deactivate_confirm')) ?>');"><?= $escape(t('voxel_desktop.deactivate')) ?></button></form><?php endif; ?>
    </div></td></tr>
<?php endforeach; ?>
<?php if (!$destinations): ?><tr><td colspan="6" class="text-muted"><?= $escape(t('voxel_desktop.empty')) ?></td></tr><?php endif; ?>
</tbody></table></div></div></div>

<div class="card border-warning shadow-sm mb-4"><div class="card-body"><h2 class="h5 mb-2"><?= $escape(t('voxel_desktop.manual_test_title')) ?></h2><p class="small text-muted"><?= $escape(t('voxel_desktop.manual_test_help')) ?></p>
<?php if ($manualDestinations): ?><form method="post" action="/platform/negocios/<?= (int)$tenant['id'] ?>/voxel-desktop/manual-tests" class="row g-3"><input type="hidden" name="_csrf_token" value="<?= $escape($csrfToken) ?>"><div class="col-md-4"><label class="form-label" for="vd-manual-destination"><?= $escape(t('voxel_desktop.manual_test_destination')) ?></label><select id="vd-manual-destination" name="destination_id" class="form-select" required><?php foreach($manualDestinations as $destination): ?><option value="<?= (int)$destination['id'] ?>"><?= $escape($destination['nome']) ?></option><?php endforeach; ?></select></div><div class="col-md-8"><label class="form-label" for="vd-manual-report-token"><?= $escape(t('voxel_desktop.manual_test_report')) ?></label><input id="vd-manual-report-token" class="form-control" name="report_public_token" maxlength="512" required autocomplete="off"><div class="form-text"><?= $escape(t('voxel_desktop.manual_test_report_help')) ?></div></div><div class="col-12"><div class="form-check"><input class="form-check-input" id="vd-confirm-manual-test" type="checkbox" name="confirm_single_manual_test" value="1" required><label class="form-check-label" for="vd-confirm-manual-test"><?= $escape(t('voxel_desktop.manual_test_confirm')) ?></label></div></div><div class="col-12"><button class="btn btn-warning" type="submit"><?= $escape(t('voxel_desktop.manual_test_prepare')) ?></button></div></form><?php else: ?><div class="alert alert-secondary mb-0 small"><?= $escape(t('voxel_desktop.manual_test_no_destination')) ?></div><?php endif; ?>
<div class="table-responsive mt-4"><table class="table table-sm"><thead><tr><th><?= $escape(t('voxel_desktop.manual_test_destination')) ?></th><th><?= $escape(t('voxel_desktop.status')) ?></th><th><?= $escape(t('voxel_desktop.manual_test_expires')) ?></th><th><?= $escape(t('voxel_desktop.updated')) ?></th></tr></thead><tbody><?php foreach($manualTests as $test): ?><tr><td><?= $escape($test['destination_name']) ?></td><td><?= $escape(t('voxel_desktop.manual_test_status.'.(string)$test['status'])) ?></td><td><?= $escape($test['expires_at']) ?></td><td><?= $escape($test['updated_at']) ?></td></tr><?php endforeach; ?><?php if(!$manualTests): ?><tr><td colspan="4" class="text-muted"><?= $escape(t('voxel_desktop.manual_test_empty')) ?></td></tr><?php endif; ?></tbody></table></div>
</div></div>

<div class="card shadow-sm mt-4"><div class="card-body"><h2 class="h5 mb-1"><?= $escape(t('voxel_desktop.logs_title')) ?></h2><p class="text-muted small mb-3"><?= $escape(t('voxel_desktop.logs_help')) ?></p><div class="table-responsive"><table class="table table-sm"><thead><tr><th><?= $escape(t('voxel_desktop.logs_time')) ?></th><th><?= $escape(t('voxel_desktop.logs_source')) ?></th><th><?= $escape(t('voxel_desktop.logs_event')) ?></th><th><?= $escape(t('voxel_desktop.logs_status')) ?></th></tr></thead><tbody><?php foreach ($technicalLogs as $log): ?><tr><td><?= $escape($log['occurred_at']) ?></td><td><?= $escape(t('voxel_desktop.logs.source.'.(string)$log['source'])) ?></td><td><?= $escape(t('voxel_desktop.logs.event.'.(string)$log['event'])) ?></td><td><?= $escape(t('voxel_desktop.logs.status.'.(string)$log['status'])) ?></td></tr><?php endforeach; ?><?php if (!$technicalLogs): ?><tr><td colspan="4" class="text-muted"><?= $escape(t('voxel_desktop.logs_empty')) ?></td></tr><?php endif; ?></tbody></table></div></div></div>

<script>
(() => {
  const form=document.getElementById('voxel-destination-form'); const title=document.getElementById('destination-form-title'); const cancel=document.getElementById('vd-cancel-edit');
  document.querySelectorAll('.vd-edit').forEach(button => button.addEventListener('click', () => { const d=JSON.parse(button.dataset.destination); form.action='/platform/negocios/<?= (int)$tenant['id'] ?>/voxel-desktop/destinations/'+d.id; ['nome','router_id','site_id','issuer_of_patient_id_normalized','institution_name'].forEach(k=>form.elements[k].value=d[k]||''); form.elements.ambiente.value=d.ambiente||'homologacao'; document.getElementById('vd-token').value=''; document.getElementById('vd-token-help').textContent='<?= $escape(t('voxel_desktop.edit_token_help')) ?>'; title.textContent='<?= $escape(t('voxel_desktop.edit_title')) ?>'; cancel.classList.remove('d-none'); window.scrollTo({top:0,behavior:'smooth'}); }));
  cancel?.addEventListener('click',()=>location.reload());
})();
</script>
