-- =============================================================================
-- Migração PostgreSQL: Portal de Resultados — imagens DICOM anonimizadas
-- Data: 2026-08-20 | Sistema: VOXEL PACS
-- Ambiente: PostgreSQL 16+ | Escopo: homologação segura da arquitetura B
-- =============================================================================
-- Não habilita imagens. Estrutura somente para cópias anonimizadas separadas,
-- sessões temporárias de um estudo e auditoria sem persistir tokens em claro.
-- =============================================================================

CREATE TABLE IF NOT EXISTS bi_portal_anonymized_studies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    source_estudo_id BIGINT NOT NULL,
    source_orthanc_id VARCHAR(64) NOT NULL,
    source_study_uid VARCHAR(128) NOT NULL,
    repository_key VARCHAR(32) NOT NULL DEFAULT 'portal-anonymized',
    anonymized_orthanc_id VARCHAR(64) NULL,
    anonymized_study_uid VARCHAR(128) NULL,
    profile_version VARCHAR(32) NOT NULL,
    state VARCHAR(16) NOT NULL DEFAULT 'pending',
    pixel_review_status VARCHAR(16) NOT NULL DEFAULT 'pending',
    pixel_reviewed_at TIMESTAMPTZ NULL,
    pixel_reviewed_by BIGINT NULL,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processing_at TIMESTAMPTZ NULL,
    prepared_at TIMESTAMPTZ NULL,
    expires_at TIMESTAMPTZ NULL,
    purged_at TIMESTAMPTZ NULL,
    failed_at TIMESTAMPTZ NULL,
    failure_code VARCHAR(64) NULL,
    failure_detail VARCHAR(255) NULL,
    retry_count SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_portal_anonymized_source UNIQUE (tenant_id, source_estudo_id, repository_key),
    CONSTRAINT chk_portal_anonymized_state CHECK (state IN ('pending', 'processing', 'ready', 'failed', 'expired', 'purged')),
    CONSTRAINT chk_portal_anonymized_pixel_review CHECK (pixel_review_status IN ('pending', 'approved', 'rejected'))
);

CREATE INDEX IF NOT EXISTS idx_portal_anonymized_worker
    ON bi_portal_anonymized_studies (state, requested_at);
CREATE INDEX IF NOT EXISTS idx_portal_anonymized_expiry
    ON bi_portal_anonymized_studies (state, expires_at);
CREATE INDEX IF NOT EXISTS idx_portal_anonymized_source_orthanc
    ON bi_portal_anonymized_studies (tenant_id, source_orthanc_id);

CREATE TABLE IF NOT EXISTS bi_portal_image_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash CHAR(64) NOT NULL UNIQUE,
    report_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    estudo_id BIGINT NOT NULL,
    anonymized_study_id BIGINT NOT NULL,
    identity_hash CHAR(64) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    user_agent_hash CHAR(64) NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    opened_at TIMESTAMPTZ NULL,
    last_accessed_at TIMESTAMPTZ NULL,
    revoked_at TIMESTAMPTZ NULL,
    access_count SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_portal_image_session_access CHECK (access_count >= 0)
);

CREATE INDEX IF NOT EXISTS idx_portal_image_session_validation
    ON bi_portal_image_sessions (token_hash, expires_at, revoked_at);
CREATE INDEX IF NOT EXISTS idx_portal_image_session_report
    ON bi_portal_image_sessions (report_id, tenant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_portal_image_session_expiry
    ON bi_portal_image_sessions (expires_at, revoked_at);

CREATE TABLE IF NOT EXISTS bi_portal_image_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_session_id BIGINT NULL,
    tenant_id BIGINT NOT NULL,
    report_id BIGINT NOT NULL,
    event_type VARCHAR(32) NOT NULL,
    outcome VARCHAR(16) NOT NULL,
    http_status SMALLINT NULL,
    ip_address VARCHAR(45) NULL,
    request_path VARCHAR(255) NULL,
    detail_code VARCHAR(64) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_portal_image_audit_event CHECK (event_type IN ('queued', 'prepared', 'session_issued', 'gateway_allowed', 'gateway_denied', 'expired', 'purged', 'failed')),
    CONSTRAINT chk_portal_image_audit_outcome CHECK (outcome IN ('allowed', 'denied', 'info', 'error'))
);

CREATE INDEX IF NOT EXISTS idx_portal_image_audit_session_created
    ON bi_portal_image_audit (image_session_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_portal_image_audit_report_created
    ON bi_portal_image_audit (report_id, tenant_id, created_at DESC);

-- VALIDAÇÃO
SELECT COUNT(*) AS total_copias_anonimizadas FROM bi_portal_anonymized_studies;
SELECT COUNT(*) AS total_sessoes_imagem FROM bi_portal_image_sessions;
SELECT COUNT(*) AS total_auditorias_imagem FROM bi_portal_image_audit;

-- ROLLBACK (executar somente se nenhuma sessão/cópia de homologação precisar ser preservada)
-- DROP TABLE IF EXISTS bi_portal_image_audit;
-- DROP TABLE IF EXISTS bi_portal_image_sessions;
-- DROP TABLE IF EXISTS bi_portal_anonymized_studies;
