-- =============================================================================
-- Migração PostgreSQL: Portal de Resultados para Pacientes
-- Data: 2026-08-20 | Sistema: VOXEL PACS
-- Ambiente: PostgreSQL 16+ (schema ativo da aplicação)
-- =============================================================================
-- Cria estruturas isoladas para rate limiting, desafios de instituição e
-- sessões temporárias. Não altera estudos, laudos ou pacientes.
--
-- A migration é idempotente e pode ser executada na homologação PostgreSQL.
-- =============================================================================

CREATE TABLE IF NOT EXISTS bi_portal_login_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ip_address VARCHAR(45) NOT NULL,
    identity_hash CHAR(64) NOT NULL,
    etapa SMALLINT NOT NULL,
    sucesso SMALLINT NOT NULL DEFAULT 0,
    blocked_until TIMESTAMPTZ NULL,
    user_agent VARCHAR(255) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_portal_attempt_ip_created
    ON bi_portal_login_attempts (ip_address, created_at);
CREATE INDEX IF NOT EXISTS idx_portal_attempt_identity_created
    ON bi_portal_login_attempts (identity_hash, created_at);
CREATE INDEX IF NOT EXISTS idx_portal_attempt_blocked
    ON bi_portal_login_attempts (ip_address, blocked_until);

CREATE TABLE IF NOT EXISTS bi_portal_challenges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash CHAR(64) NOT NULL UNIQUE,
    identity_hash CHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    institution_name VARCHAR(255) NOT NULL,
    options_json TEXT NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_portal_challenge_expiry
    ON bi_portal_challenges (expires_at);
CREATE INDEX IF NOT EXISTS idx_portal_challenge_identity
    ON bi_portal_challenges (identity_hash, expires_at);

CREATE TABLE IF NOT EXISTS bi_portal_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash CHAR(64) NOT NULL UNIQUE,
    identity_hash CHAR(64) NOT NULL,
    tenant_id BIGINT NOT NULL,
    institution_name VARCHAR(255) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_portal_session_expiry
    ON bi_portal_sessions (expires_at);
CREATE INDEX IF NOT EXISTS idx_portal_session_identity
    ON bi_portal_sessions (identity_hash, expires_at);
