-- =============================================================================
-- Migração PostgreSQL: compartilhamento seguro do Portal de Resultados
-- Data: 2026-08-20 | Sistema: VOXEL PACS
-- Ambiente: PostgreSQL 16+ (schema ativo da aplicação)
-- =============================================================================
-- Links são opacos, temporários e vinculados a um laudo já liberado.
-- Destinatários são persistidos somente de forma mascarada para auditoria.
-- =============================================================================

CREATE TABLE IF NOT EXISTS bi_portal_share_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash CHAR(64) NOT NULL UNIQUE,
    report_id BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    channel VARCHAR(16) NOT NULL,
    recipient_hint VARCHAR(120) NOT NULL,
    creator_identity_hash CHAR(64) NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ NULL,
    access_count SMALLINT NOT NULL DEFAULT 0,
    revoked_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_portal_share_channel CHECK (channel IN ('whatsapp', 'email'))
);

CREATE INDEX IF NOT EXISTS idx_portal_share_token_expiry
    ON bi_portal_share_links (token_hash, expires_at);
CREATE INDEX IF NOT EXISTS idx_portal_share_report_created
    ON bi_portal_share_links (report_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_portal_share_tenant_expiry
    ON bi_portal_share_links (tenant_id, expires_at);
