-- MVP Agendamentos: paridade MySQL/MariaDB.
CREATE TABLE IF NOT EXISTS bi_agendamentos (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT UNSIGNED NOT NULL,
    unidade_id BIGINT UNSIGNED NOT NULL,
    pacs_id BIGINT UNSIGNED NOT NULL,
    accession_number VARCHAR(16) NOT NULL,
    patient_id VARCHAR(32) NOT NULL,
    patient_name VARCHAR(64) NOT NULL,
    patient_birth_date DATE NOT NULL,
    modalidade VARCHAR(16) NOT NULL,
    data_agendada DATE NOT NULL,
    hora_agendada TIME NULL,
    situacao ENUM('agendado','realizado','cancelado') NOT NULL DEFAULT 'agendado',
    mwl_status ENUM('aguardando_infraestrutura','pendente_publicacao','publicado','erro') NOT NULL DEFAULT 'aguardando_infraestrutura',
    estudo_id BIGINT UNSIGNED NULL,
    realizado_em DATETIME NULL,
    cancelado_por BIGINT UNSIGNED NULL,
    cancelado_em DATETIME NULL,
    criado_por BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_agendamentos_accession (accession_number),
    KEY idx_agendamentos_tenant_status_data (tenant_id, situacao, data_agendada, hora_agendada),
    KEY idx_agendamentos_correlacao (tenant_id, pacs_id, accession_number),
    CONSTRAINT fk_agendamentos_tenant FOREIGN KEY (tenant_id) REFERENCES bi_tenants(id),
    CONSTRAINT fk_agendamentos_unidade FOREIGN KEY (unidade_id) REFERENCES bi_unidades(id),
    CONSTRAINT fk_agendamentos_pacs FOREIGN KEY (pacs_id) REFERENCES bi_pacs_servidor(id),
    CONSTRAINT fk_agendamentos_estudo FOREIGN KEY (estudo_id) REFERENCES bi_pacs_estudos(id),
    CONSTRAINT fk_agendamentos_cancelado_por FOREIGN KEY (cancelado_por) REFERENCES bi_users(id),
    CONSTRAINT fk_agendamentos_criado_por FOREIGN KEY (criado_por) REFERENCES bi_users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
