<!-- Catálogo Downloads: mostra produto, telemetria agregada e exclusão apenas de rascunho não publicado. -->
<!-- Materialização de runtime para publicação restrita da separação de produtos. -->
<div class="container-fluid py-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <div><h1 class="h3 mb-1"><?= htmlspecialchars(t('downloads.title')) ?></h1><p class="text-muted mb-0"><?= htmlspecialchars(t('downloads.subtitle')) ?></p></div>
        <a class="btn btn-primary" href="/platform/downloads/new"><i class="fa fa-upload me-1"></i><?= htmlspecialchars(t('downloads.new')) ?></a>
    </div>
    <?php if (!empty($_SESSION['success'])): ?><div class="alert alert-success"><?= htmlspecialchars((string) $_SESSION['success']); unset($_SESSION['success']); ?></div><?php endif; ?>
    <?php if (!empty($_SESSION['error'])): ?><div class="alert alert-danger"><?= htmlspecialchars((string) $_SESSION['error']); unset($_SESSION['error']); ?></div><?php endif; ?>
    <div class="card shadow-sm"><div class="table-responsive"><table class="table table-hover mb-0 align-middle"><thead><tr><th><?= htmlspecialchars(t('downloads.product')) ?></th><th><?= htmlspecialchars(t('downloads.version')) ?></th><th><?= htmlspecialchars(t('downloads.platform')) ?></th><th><?= htmlspecialchars(t('downloads.channel')) ?></th><th><?= htmlspecialchars(t('downloads.status')) ?></th><th><?= htmlspecialchars(t('downloads.download_count')) ?></th><th><?= htmlspecialchars(t('downloads.created')) ?></th><th class="text-end"><?= htmlspecialchars(t('downloads.actions')) ?></th></tr></thead><tbody>
    <?php foreach ($packages as $package): ?>
        <?php $productKey = (string) ($package['product_key'] ?? 'voxel_desktop'); $isCurrentProduct = in_array($productKey, ['voxel_view_desktop', 'voxel_router_desktop'], true); ?>
        <tr><td><?= htmlspecialchars(t('downloads.product.' . $productKey)) ?></td><td><strong><?= htmlspecialchars((string) $package['version_name']) ?></strong><br><small class="text-muted"><?= htmlspecialchars((string) $package['original_filename']) ?></small></td><td><?= htmlspecialchars((string) $package['platform']) ?></td><td><?= htmlspecialchars((string) $package['channel']) ?></td><td><span class="badge text-bg-<?= ($package['status'] ?? '') === 'published' ? 'success' : (($package['status'] ?? '') === 'draft' ? 'secondary' : 'dark') ?>"><?= htmlspecialchars(t('downloads.status.' . (string) $package['status'])) ?></span></td><td><?= (int) ($package['downloads'] ?? 0) ?></td><td><?= htmlspecialchars((string) $package['created_at']) ?></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="/platform/downloads/<?= (int) $package['id'] ?>/statistics"><?= htmlspecialchars(t('downloads.statistics')) ?></a><?php if (($package['status'] ?? '') === 'draft' && $isCurrentProduct): ?><form class="d-inline" method="post" action="/platform/downloads/<?= (int) $package['id'] ?>/publish"><input type="hidden" name="_csrf_token" value="<?= htmlspecialchars((string) $csrfToken) ?>"><button class="btn btn-sm btn-success" type="submit"><?= htmlspecialchars(t('downloads.publish')) ?></button></form><?php endif; ?><?php if (($package['status'] ?? '') === 'published'): ?><form class="d-inline" method="post" action="/platform/downloads/<?= (int) $package['id'] ?>/archive"><input type="hidden" name="_csrf_token" value="<?= htmlspecialchars((string) $csrfToken) ?>"><button class="btn btn-sm btn-outline-danger" type="submit"><?= htmlspecialchars(t('downloads.archive')) ?></button></form><?php elseif (($package['status'] ?? '') === 'draft'): ?><form class="d-inline" method="post" action="/platform/downloads/<?= (int) $package['id'] ?>/delete" onsubmit="return confirm(this.dataset.confirm)" data-confirm="<?= htmlspecialchars(t('downloads.delete_confirm')) ?>"><input type="hidden" name="_csrf_token" value="<?= htmlspecialchars((string) $csrfToken) ?>"><button class="btn btn-sm btn-outline-danger" type="submit"><?= htmlspecialchars(t('downloads.delete')) ?></button></form><?php endif; ?></td></tr>
    <?php endforeach; ?>
    <?php if (!$packages): ?><tr><td colspan="8" class="text-center text-muted py-5"><?= htmlspecialchars(t('downloads.empty')) ?></td></tr><?php endif; ?>
    </tbody></table></div></div>
</div>
