<?php
/** Estilo: formulário PACS tenant-scoped; cada regra é opt-in e seus campos são explicitamente dependentes. */
$selectedDays = array_flip(array_filter(array_map('intval', explode(',', (string) ($regra['horario_dias_semana'] ?? '1,2,3,4,5,6,7')))));
$dayLabels = [1 => t('usuarios.regras_acesso.seg'), 2 => t('usuarios.regras_acesso.ter'), 3 => t('usuarios.regras_acesso.qua'), 4 => t('usuarios.regras_acesso.qui'), 5 => t('usuarios.regras_acesso.sex'), 6 => t('usuarios.regras_acesso.sab'), 7 => t('usuarios.regras_acesso.dom')];
?>
<div class="container-fluid py-4"><div class="mb-3"><a href="/usuarios/regras-acesso" class="text-decoration-none"><i class="fa fa-arrow-left me-1"></i><?= htmlspecialchars(t('usuarios.regras_acesso.voltar')) ?></a></div>
<div class="row justify-content-center"><div class="col-xl-9"><div class="pacs-card p-4"><h1 class="h3 mb-1"><?= htmlspecialchars(t('usuarios.regras_acesso.editar_titulo')) ?></h1><p class="text-muted mb-4"><?= htmlspecialchars((string) $usuario['name']) ?> · <?= htmlspecialchars((string) ($usuario['perfil'] ?? '')) ?></p>
<?php if ($erro !== ''): ?><div class="pacs-alert pacs-alert-danger"><i class="fa fa-exclamation-triangle me-2"></i><?= htmlspecialchars(t('usuarios.regras_acesso.' . $erro)) ?></div><?php endif; ?>
<form method="post" action="/usuarios/regras-acesso/<?= (int) $usuario['id'] ?>/salvar" id="access-rule-form"><input type="hidden" name="_csrf_token" value="<?= htmlspecialchars($csrf) ?>">
<section class="border rounded p-3 mb-3"><div class="form-check form-switch mb-3"><input class="form-check-input rule-toggle" type="checkbox" id="timeout-active" name="sessao_timeout_ativo" <?= (int) ($regra['sessao_timeout_ativo'] ?? 0) === 1 ? 'checked' : '' ?>><label class="form-check-label fw-semibold" for="timeout-active"><?= htmlspecialchars(t('usuarios.regras_acesso.timeout_ativo')) ?></label></div><label class="form-label" for="timeout-minutes"><?= htmlspecialchars(t('usuarios.regras_acesso.timeout_minutos')) ?></label><input id="timeout-minutes" class="form-control form-control-dark rule-dependent-timeout" type="number" min="5" max="480" name="sessao_timeout_minutos" value="<?= htmlspecialchars((string) ($regra['sessao_timeout_minutos'] ?? '')) ?>"><div class="form-text"><?= htmlspecialchars(t('usuarios.regras_acesso.timeout_ajuda')) ?></div></section>
<section class="border rounded p-3 mb-3"><div class="form-check form-switch mb-3"><input class="form-check-input rule-toggle" type="checkbox" id="ip-active" name="ip_restricao_ativa" <?= (int) ($regra['ip_restricao_ativa'] ?? 0) === 1 ? 'checked' : '' ?>><label class="form-check-label fw-semibold" for="ip-active"><?= htmlspecialchars(t('usuarios.regras_acesso.ip_ativo')) ?></label></div><label class="form-label" for="ip-list"><?= htmlspecialchars(t('usuarios.regras_acesso.ip_lista')) ?></label><textarea id="ip-list" class="form-control form-control-dark rule-dependent-ip" rows="5" name="ip_lista_permitida" maxlength="4096"><?= htmlspecialchars((string) ($regra['ip_lista_permitida'] ?? '')) ?></textarea><div class="form-text"><?= htmlspecialchars(t('usuarios.regras_acesso.ip_ajuda')) ?></div></section>
<section class="border rounded p-3 mb-4"><div class="form-check form-switch mb-3"><input class="form-check-input rule-toggle" type="checkbox" id="schedule-active" name="horario_restricao_ativa" <?= (int) ($regra['horario_restricao_ativa'] ?? 0) === 1 ? 'checked' : '' ?>><label class="form-check-label fw-semibold" for="schedule-active"><?= htmlspecialchars(t('usuarios.regras_acesso.horario_ativo')) ?></label></div><div class="row g-3 rule-dependent-schedule"><div class="col-md-4"><label class="form-label" for="schedule-start"><?= htmlspecialchars(t('usuarios.regras_acesso.inicio')) ?></label><input id="schedule-start" class="form-control form-control-dark" type="time" name="horario_inicio" value="<?= htmlspecialchars(substr((string) ($regra['horario_inicio'] ?? ''), 0, 5)) ?>"></div><div class="col-md-4"><label class="form-label" for="schedule-end"><?= htmlspecialchars(t('usuarios.regras_acesso.fim')) ?></label><input id="schedule-end" class="form-control form-control-dark" type="time" name="horario_fim" value="<?= htmlspecialchars(substr((string) ($regra['horario_fim'] ?? ''), 0, 5)) ?>"></div><div class="col-md-12"><label class="form-label d-block"><?= htmlspecialchars(t('usuarios.regras_acesso.dias')) ?></label><?php foreach ($dayLabels as $day => $label): ?><div class="form-check form-check-inline"><input class="form-check-input" type="checkbox" id="day-<?= $day ?>" name="horario_dias_semana[]" value="<?= $day ?>" <?= isset($selectedDays[$day]) ? 'checked' : '' ?>><label class="form-check-label" for="day-<?= $day ?>"><?= htmlspecialchars($label) ?></label></div><?php endforeach; ?></div></div><div class="form-text mt-2"><?= htmlspecialchars(t('usuarios.regras_acesso.horario_ajuda')) ?></div></section>
<div class="d-flex justify-content-end gap-2"><a class="btn btn-outline-secondary" href="/usuarios/regras-acesso"><?= htmlspecialchars(t('usuarios.regras_acesso.cancelar')) ?></a><button class="btn btn-pacs-primary" type="submit"><i class="fa fa-save me-1"></i><?= htmlspecialchars(t('usuarios.regras_acesso.salvar')) ?></button></div></form>
</div></div></div></div>
<script>
(() => { const pairs = [['timeout-active','.rule-dependent-timeout'],['ip-active','.rule-dependent-ip'],['schedule-active','.rule-dependent-schedule input']]; pairs.forEach(([id,selector]) => { const toggle = document.getElementById(id); const sync = () => document.querySelectorAll(selector).forEach(field => field.disabled = !toggle.checked); toggle.addEventListener('change', sync); sync(); }); })();
</script>
