<?php
$status = (string) ($resultado['status'] ?? 'invalido');
$valido = $status === 'valido';
$titulo = $valido ? t('auditoria.validacao.valido.titulo') : ($status === 'expirado' ? t('auditoria.validacao.expirado.titulo') : t('auditoria.validacao.invalido.titulo'));
$descricao = $valido ? t('auditoria.validacao.valido.descricao') : ($status === 'expirado' ? t('auditoria.validacao.expirado.descricao') : t('auditoria.validacao.invalido.descricao'));
$tipos = ['acesso' => t('auditoria.tipo.acesso'), 'estudos' => t('auditoria.tipo.estudos'), 'clinica' => t('auditoria.tipo.clinica')];
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= htmlspecialchars($titulo) ?> | VOXEL PACS</title><style>
body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:#eef3f9;color:#14233d;font-family:Arial,sans-serif}.card{width:min(100%,600px);background:#fff;border:1px solid #d9e3ef;border-radius:14px;box-shadow:0 16px 40px rgba(25,50,84,.12);overflow:hidden}.bar{height:7px;background:<?= $valido ? '#1a8f58' : '#b42318' ?>}.content{padding:32px}.eyebrow{font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#52677f}.status{margin:10px 0;font-size:25px}.text{line-height:1.55;color:#4f6278}.grid{margin-top:24px;border-top:1px solid #e5edf5}.item{display:flex;gap:16px;padding:13px 0;border-bottom:1px solid #e5edf5}.item b{width:155px;color:#52677f;font-size:13px}.item span{font-size:14px}.notice{margin-top:20px;padding:12px;border-radius:8px;background:#f6f8fb;color:#596c83;font-size:12px;line-height:1.45}.brand{margin-top:22px;color:#6a7b90;font-size:12px;font-weight:700}</style></head><body><main class="card"><div class="bar"></div><div class="content"><div class="eyebrow"><?= htmlspecialchars(t('auditoria.validacao.eyebrow')) ?></div><h1 class="status"><?= htmlspecialchars($titulo) ?></h1><p class="text"><?= htmlspecialchars($descricao) ?></p><?php if ($valido): ?><div class="grid"><div class="item"><b><?= htmlspecialchars(t('auditoria.validacao.tenant')) ?></b><span><?= htmlspecialchars($resultado['tenant_nome']) ?></span></div><div class="item"><b><?= htmlspecialchars(t('auditoria.validacao.documento')) ?></b><span><?= htmlspecialchars(t('auditoria.pdf.titulo')) ?> — <?= htmlspecialchars($tipos[$resultado['tipo']] ?? t('auditoria.titulo')) ?> (<?= htmlspecialchars($resultado['formato']) ?>)</span></div><div class="item"><b><?= htmlspecialchars(t('auditoria.validacao.emitido_em')) ?></b><span><?= htmlspecialchars($resultado['emitido_em']->format('d/m/Y H:i:s')) ?></span></div><div class="item"><b><?= htmlspecialchars(t('auditoria.validacao.autenticado_em')) ?></b><span><?= htmlspecialchars($resultado['validado_em']->format('d/m/Y H:i:s')) ?></span></div><div class="item"><b><?= htmlspecialchars(t('auditoria.validacao.codigo')) ?></b><span><?= htmlspecialchars($resultado['codigo_publico']) ?></span></div><div class="item"><b><?= htmlspecialchars(t('auditoria.validacao.integridade')) ?></b><span><?= htmlspecialchars($resultado['codigo_integridade']) ?></span></div></div><p class="notice"><?= htmlspecialchars(!empty($resultado['primeira_validacao']) ? t('auditoria.validacao.primeira') : t('auditoria.validacao.reconsulta')) ?> <?= htmlspecialchars(t('auditoria.validacao.privacidade')) ?></p><?php endif; ?><div class="brand">VOXEL PACS · <?= htmlspecialchars(t('auditoria.validacao.marca')) ?></div></div></main></body></html>
